name: Deploy Go App to VPS

on:
  push:
    branches:
      - prod  # Trigger the deployment when code is pushed to the `prod` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Add VPS to known_hosts to avoid SSH verification issues
      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      # Deploy via SSH using the VPS password
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.SSH_PASSWORD }}  # Using password-based authentication
          port: 22
          script: |
            set -x  # Enable debug output for the shell script

            # Navigate to the home directory of the VPS user
            cd /home/${{ secrets.VPS_USER }}

            # Clone the repository if it doesn't exist, otherwise pull the latest changes
            if [ ! -d "jse" ]; then
              echo "Cloning repository..."
              git clone https://$GITHUB_ACTOR:${{ secrets.GH_TOKEN }}@github.com/KoushikCodesWebpages/GO-Backend.git jse
            else
              cd jse
              echo "Repository already exists. Pulling latest code..."
              git fetch origin
              git reset --hard origin/prod
            fi

            cd jse

            # Stop and remove the existing Docker container if it exists
            echo "Stopping and removing existing container..."
            docker stop ${{ secrets.APP_NAME }} || true
            docker rm ${{ secrets.APP_NAME }} || true

            # Build the new Docker image
            echo "Building Docker image..."
            docker build -t ${{ secrets.APP_NAME }} .

            # Run the new Docker container
            echo "Running new container..."
            docker run -d -p 5000:5000 --name ${{ secrets.APP_NAME }} ${{ secrets.APP_NAME }}
