name: Deploy Go App to VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Add VPS to known_hosts to avoid SSH verification issues
      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      # Deploy via SSH using the VPS password
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.SSH_PASSWORD }}  # Using the password here
          port: 22
          script: |
            set -x  # This enables debug output for the shell script
            cd /home/${{ secrets.VPS_USER }}

            if [ ! -d "git-jse" ]; then
              echo "Cloning repository..."
              git clone https://github.com/KoushikCodesWebpages/GO-Backend.git git-jse
            else
              cd jse
              echo "Repository already exists. Pulling latest code..."
              git fetch origin
              git reset --hard origin/prod
            fi

            cd jse

            echo "Stopping and removing existing container..."
            docker stop ${{ secrets.APP_NAME }} || true
            docker rm ${{ secrets.APP_NAME }} || true

            echo "Building Docker image..."
            docker build -t ${{ secrets.APP_NAME }} .

            echo "Running new container..."
            docker run -p 8000:8000 --name ${{ secrets.APP_NAME  }} ${{ secrets.APP_NAME }}
